feat(api/events): add news controllers and utils
yoVoy-pf/yoVoy pull request #179
Opened 2022-06-16 22:45 UTC by Elevattd

Se agrega nueva busqueda por nombre del evento, para buscar por dicha propiedad, para renderizar los evento por locacion.

2022-06-17 01:17 UTC, FireDash22 approved these changes

2022-06-17 01:27 UTC, Diego-Avila-Acosta requested changes

2022-06-17 01:27 UTC, Diego-Avila-Acosta commented on api/src/utils/events.ts
> +	}
Por que se necesitaria incluir mas relaciones si no se van a mostrar?

2022-06-17 01:46 UTC, Elevattd commented on api/src/utils/events.ts
> +	}
Si se van a mostrar.

2022-06-17 15:07 UTC, FmtGomez approved these changes

2022-06-18 22:50 UTC, WorkdayLucas approved these changes

2022-06-19 01:45 UTC, Diego-Avila-Acosta commented on api/src/controllers/events.ts
> +		const name = req.query.name as string;
Si se quiere mas información mas para el search se cambia el query y no se duplica la función

2022-06-19 17:58 UTC, closed without merging